# Generated by Django 4.1.1 on 2022-11-02 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('activity', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=10)),
                ('current_add', models.CharField(max_length=100)),
                ('prn', models.BigIntegerField()),
                ('roll', models.BigIntegerField()),
                ('contact_num', models.FloatField()),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IsCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=10)),
                ('activity', models.CharField(default='', max_length=30)),
                ('dept', models.CharField(default='', max_length=20)),
                ('academic_year', models.CharField(default='', max_length=10)),
                ('module', models.CharField(default='', max_length=20)),
                ('div', models.CharField(default='', max_length=10)),
                ('current_add', models.CharField(default='', max_length=100)),
                ('prn', models.BigIntegerField(default=0)),
                ('roll', models.BigIntegerField(default=0)),
                ('contact_num', models.FloatField(default=0)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
