# Generated by Django 4.1.1 on 2022-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
