# Generated by Django 4.1.3 on 2022-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_vdata_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdata',
            name='Benefits_to_Self',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vdata',
            name='Benefits_to_Society',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vdata',
            name='Description_of_the_Activity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vdata',
            name='How_did_it_help_you_to_shape_your_Empathy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vdata',
            name='Learning_Experiences_challenges',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vdata',
            name='Objective_of_the_Activity',
            field=models.CharField(default='', max_length=200),
        ),
    ]
