# Generated by Django 4.1.3 on 2022-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_vdata_benefits_to_self_vdata_benefits_to_society_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdata',
            name='Cordinator',
            field=models.CharField(default='', max_length=40),
        ),
    ]
